### ISSUE TITLE
.

### ISSUE THREAD

**Issue by cintagram** [TheAxes/Discord-Nuke-Bot#4]

**Comment by TheAxes** [comment]
Your code link dude

**Comment by cintagram** [comment]
oh wait...i saw it wrong
your nuker and mine have very similar code structure and nuking methods.
sorry for oversight ;-;

(you can see my nuker on my github (cintagram/Pulse_Nuker)

**Comment by TheAxes** [comment]
Funfact: mine is 2yr old and urs is just 8 months

Noice boi
